source_set("Kernel") {
  sources = [
    "PreComp.h",
    "Base64.cpp",
    "CArchiver.cpp",
    "CArrayBase.cpp",
    "CAtomTable.cpp",
    "CAtomizer.cpp",
    "CConsoleFormat.cpp",
    "CDataFile.cpp",
    "CDictionary.cpp",
    "CException.cpp",
    "CFileDirectory.cpp",
    "CFileReadBlock.cpp",
    "CFileReadStream.cpp",
    "CFileWriteStream.cpp",
    "CGeometry.cpp",
    "CHTML.cpp",
    "CHTMLForm.cpp",
    "CHTTPClientSession.cpp",
    "CHTTPMessage.cpp",
    "CIDTable.cpp",
    "CINTDynamicArray.cpp",
    "CIntArray.cpp",
    "CIntGraph.cpp",
    "CIntegerIP.cpp",
    "CLabelArranger.cpp",
    "CLargeSet.cpp",
    "CManualEvent.cpp",
    "CMapBase.cpp",
    "CMarkovWordGenerator.cpp",
    "CMemoryStream.cpp",
    "CObject.cpp",
    "CPeriodicWaiter.cpp",
    "CPolygon.cpp",
    "CProjection3D.cpp",
    "CRegKey.cpp",
    "CResourceReadBlock.cpp",
    "CSphericalCoordinates.cpp",
    "CStackBase.cpp",
    "CStepIncrementor.cpp",
    "CString.cpp",
    "CSymbolTable.cpp",
    "CTextFileLog.cpp",
    "CThreadPool.cpp",
    "CVector.cpp",
    "CVoronoiTessellation.cpp",
    "CWordParser.cpp",
    "CXForm3D.cpp",
    "CalcConvexHull.cpp",
    "CryptoRandom.cpp",
    "Euclid.cpp",
    "ILog.cpp",
    "InternetsUtil.cpp",
    "Kernel.cpp",
    "Math.cpp",
    "Path.cpp",
    "Pattern.cpp",
    "RegEx.cpp",
    "RunLengthCompression.cpp",
    "SecureHashAlgorithm.cpp",
    "Shapes.cpp",
    "Time.cpp",
    "UI.cpp",
    "Unicode.cpp",
    "Utilities.cpp",
    "Voronoi.cpp",
    "VoronoiGenerator.cpp",
    "VoronoiGenerator.h",
    "XForm.cpp",
    "quickhull/QuickHull.cpp",
    "quickhull/QuickHull.hpp",
    "Zip.cpp",
    "ZipArchive.cpp",
  ]
  public_deps = [
    "../Include:Kernel",
  ]
  deps = [
    "../zlib-1.2.7:zlib",
  ]
  include_dirs = [
    ".",
  ]
}
