import("//gn/tbd.gni")

group("everything") {
  deps = [
    "Alchemy/Kernel",
    "Alchemy/XMLUtil",
    "Alchemy/CodeChain",
    "Alchemy/Graphics",
    "Alchemy/DirectXUtil",
    "Alchemy/IntelJPEGUtil",
    "Mammoth/TSE",
    "Mammoth/TSUI",
    "Transcendence/TransCompiler",

    # Unclear if DirectXFont builds.
    # "Alchemy/DirectXFont",

    # NetUtil does not build (missing CSharedObjectQueue, CStructArray)
    #"Alchemy/NetUtil",

    #"Alchemy/CCShell",
    #"Alchemy/CCLink",
  ]
}

executable("unittests") {
  testonly = true
  deps = [
    "deps/googletest:gtest_main",
    "smoke:unittests",
  ]
}

executable("TransCompiler") {
  deps = [
    "//Transcendence/TransCompiler",
  ]
}

executable("Transcendence") {
  deps = [
    "//Transcendence/Transcendence:TranscendenceMain",
  ]
}

copy("package_exe") {
  sources = [
    "$root_build_dir/Transcendence",
  ]
  outputs = [
    "$root_build_dir/game/{{source_name_part}}.exe",
  ]
  deps = [
    ":Transcendence",
  ]
}

tbd("package_tbd") {
  input = "//Transcendence/TransCore/Transcendence.xml"
  output = "$root_build_dir/game/Transcendence.tdb"
}

group("package") {
  deps = [
    ":package_exe",
    ":package_tbd",
  ]
}

