# Arguments:
# - input: root .xml file
# - output: output path for .tbd file
template("tbd") {
  assert(defined(invoker.input), "input must be defined")
  assert(defined(invoker.output), "output must be defined")

  name = target_name

  action(name) {
    forward_variables_from(invoker,
                           [
                             "testonly",
                             "deps",
                             "sources",
                           ])

    script = "//tools/gn-run-binary"
    if (!defined(deps)) {
      deps = []
    }
    deps += [
      ":TransCompiler",
    ]
    inputs = []
    wine_path = exec_script("//tools/which", ["wine"], "trim string", [])

    args = [
      wine_path,
      "TransCompiler",
      "/input:" + rebase_path(invoker.input, root_build_dir),
      "/output:" + rebase_path(invoker.output, root_build_dir),
    ]

    outputs = [ invoker.output ]
  }
}
