#if (host_os == "win") {
#  _host_executable_suffix = ".exe"
#} else {
#  _host_executable_suffix = ""
#}
#
#template("compiled_action") {
#  assert(defined(invoker.tool), "tool must be defined for $target_name")
#  assert(defined(invoker.outputs), "outputs must be defined for $target_name")
#  assert(defined(invoker.args), "args must be defined for $target_name")
#  assert(!defined(invoker.sources),
#         "compiled_action doesn't take a sources arg. Use inputs instead.")
#
#  action(target_name) {
#    forward_variables_from(invoker,
#                           [
#                             "data_deps",
#                             "deps",
#                             "depfile",
#                             "inputs",
#                             "outputs",
#                             "testonly",
#                             "visibility",
#                           ])
#
#    if (!defined(deps)) {
#      deps = []
#    }
#
#    if (!defined(inputs)) {
#      inputs = []
#    }
#
#    meta_args = []
#    if (defined(invoker.capture_stdout)) {
#      meta_args += [ "--capture-stdout=" + invoker.capture_stdout ]
#    }
#
#    script = "//tools/gn-run-binary"
#
#    # Constuct the host toolchain version of the tool.
#    host_tool = invoker.tool + "($host_toolchain)"
#
#    host_executable =
#        get_label_info(host_tool, "root_out_dir") + "/" +
#        get_label_info(host_tool, "name") + _host_executable_suffix
#
#    deps += [ host_tool ]
#
#    host_executable_path = rebase_path(host_executable, root_build_dir)
#    args = meta_args + [ host_executable_path ] + invoker.args
#  }
#}

# Arguments:
# - sources: all source files (which must be under input)
# - input: source directory
# - output: output path
template("tbd") {
  assert(defined(invoker.input), "input must be defined")
  assert(defined(invoker.output), "output must be defined")

  name = target_name

  action(name) {
    forward_variables_from(invoker,
                           [
                             "testonly",
                             "deps",
                             "sources",
                           ])

    script = "//tools/gn-run-binary"
    inputs = [ ]
    args = [
      "/opt/homebrew/bin/wine",
      "TransCompiler",
      "/input:" + rebase_path(invoker.input, root_build_dir),
      "/output:" + rebase_path(invoker.output, root_build_dir),
    ]
    outputs = [ invoker.output ]
  }
}
