source_set("TSE") {
  sources = [
#    "CMissileItem.cpp",
#    "CMissionList.cpp",
#    "CSpaceObjectItemList.cpp",
#    "ItemProperties.cpp",
#    "CFillNodesProc.cpp",
#    "SFXSingleParticle.cpp",
#    "CSystemEventHandler.cpp",
#    "SFXSequencer.cpp",
#    "SFXOrb.cpp",
#    "CTradingEconomy.cpp",
#    "CRTFText.cpp",
#    "COrbitFocusGenerator.cpp",
#    "CApplySystemProc.cpp",
#    "CSystemMapThumbnails.cpp",
#    "PowerProperties.cpp",
#    "CParticleArray.cpp",
#    "CAutoDefenseClass.cpp",
#    "CCargoSpaceClass.cpp",
#    "CMultiverseCatalogEntry.cpp",
#    "SystemCreateImpl.h",
#    "SFXImpl.h",
#    "CTopologyNodeList.cpp",
#    "CRotationDesc.cpp",
#    "CParticleDamage.cpp",
#    "CSpaceObjectAddressResolver.cpp",
#    "CStation.cpp",
#    "CRandomItems.cpp",
#    "CMapLabelPainter.cpp",
#    "SFXParticlePattern.cpp",
#    "ShipUpdate.cpp",
#    "CMultiverseModel.cpp",
#    "CGalacticMapPainter.cpp",
#    "CTradingComputer.cpp",
#    "C3DObjectPos.cpp",
#    "CRepairerClass.cpp",
#    "CPhysicsForceDesc.cpp",
#    "CExtension.cpp",
#    "CSystemType.cpp",
#    "CCrewPsyche.cpp",
#    "CShipwreckDesc.cpp",
#    "CStationEncounterCtx.cpp",
#    "CVirtualKeyData.cpp",
#    "CItemTypeProbabilityTable.cpp",
#    "CObjectImageArray.cpp",
#    "Geometry.cpp",
#    "CItemCriteria.cpp",
#    "CConditionSet.cpp",
#    "CAchievementDef.cpp",
#    "CDeviceTable.cpp",
#    "CRadiusDamage.cpp",
#    "CPlayerGameStats.cpp",
#    "CTopologySystemDesc.cpp",
#    "CDriveDesc.cpp",
#    "CCyberDeckClass.cpp",
#    "CCommunicationsHandler.cpp",
#    "CObjectJointList.cpp",
#    "CAutoMiningCalc.cpp",
#    "CPartitionNodesProc.cpp",
#    "CIntegralRotationDesc.cpp",
#    "CShipArmorSegmentDesc.cpp",
#    "CCompositeImageType.cpp",
#    "CLocationSelectionTable.cpp",
#    "CStationHull.cpp",
#    "CTerritoryList.cpp",
#    "CVolumetricShadowPainter.cpp",
#    "CHexarc.cpp",
#    "CItemEnhancementStack.cpp",
#    "CReactorDesc.cpp",
#    "CPowerConsumption.cpp",
#    "SystemImpl.h",
#    "CInstalledDevice.cpp",
#    "CPhysicsContact.cpp",
#    "CFireEventOrder.cpp",
#    "CBoundaryMarker.cpp",
#    "CShotArray.cpp",
#    "CFireAndSmokePainter.cpp",
#    "CDelaunayStargateGenerator.cpp",
#    "CGameTimeKeeper.cpp",
#    "CStationTableCache.cpp",
#    "CCreatePainterCtx.cpp",
#    "ITopologyProcessor.cpp",
#    "CHullDesc.cpp",
#    "CSimpleOrder.cpp",
#    "IElementGenerator.cpp",
#    "CSquadronCommunications.cpp",
#    "CUniverse.cpp",
#    "CAchievementDefinitions.cpp",
#    "CEventHandler.cpp",
#    "CTopologyDesc.cpp",
#    "WeaponClassImpl.h",
#    "SFXShape.cpp",
#    "CTerritoryDef.cpp",
#    "PreComp.h",
#    "C3DConversion.cpp",
#    "CEnvironmentGrid.cpp",
#    "CZoneGrid.cpp",
#    "CScript.cpp",
#    "COverlayList.cpp",
#    "CSentryOrder.cpp",
#    "CFormulaText.cpp",
#    "CSystemMap.cpp",
#    "CDeviceStorage.cpp",
#    "COverlay.cpp",
#    "CArmorMassDefinitions.cpp",
#    "CItemEncounterDefinitions.cpp",
#    "CChallengeRatingCalculator.cpp",
#    "CParticleSystemDesc.cpp",
#    "CItemLevelCriteria.cpp",
#    "CWeaponTargetDefinition.cpp",
#    "OrderModules.cpp",
#    "CSquadronDescList.cpp",
#    "SFXRayImpl.h",
#    "COverlayUndergroundDesc.cpp",
#    "CAchievementDataBlock.cpp",
#    "CRandomPointsProc.cpp",
#    "CEffectGroupCreator.cpp",
#    "CFerianShipAI.cpp",
#    "CArmorSystem.cpp",
#    "CRangeTypeEvent.cpp",
#    "CExplosionColorizer.cpp",
#    "CImageFilterDesc.cpp",
#    "CDeterChaseOrder.cpp",
#    "CDockingPorts.cpp",
#    "CDisintegrationEffect.cpp",
#    "CDifficultyOptions.cpp",
#    "CAngleGenerator.cpp",
#    "CFailureDesc.cpp",
#    "CMultiverseCollection.cpp",
#    "SFXParticleCloud.cpp",
#    "CMoveCtx.cpp",
#    "CObjectEffectDesc.cpp",
#    "SFXText.cpp",
#    "CAutonAI.cpp",
#    "CLabelPainter.cpp",
#    "CMissionType.cpp",
#    "CTimedMissionEvent.cpp",
#    "TargetListImpl.h",
#    "CStarDesc.cpp",
#    "CAttackStationOrder.cpp",
#    "CTopologyNode.cpp",
#    "Damage.cpp",
#    "TopologyProcessorsImpl.h",
#    "PsycheDefs.h",
#    "SUpdateCtx.cpp",
#    "CPerformanceCounters.cpp",
#    "OrderModuleImpl.h",
#    "CAffinityCriteria.cpp",
#    "CTopology.cpp",
#    "CGroupTopologyProc.cpp",
#    "CAISettings.cpp",
#    "CMissionCriteria.cpp",
#    "EffectProperties.cpp",
#    "CCompositeImageSelector.cpp",
#    "CSystemTable.cpp",
#    "CSpaceObjectTrade.cpp",
#    "CPlayerSettings.cpp",
#    "CShipInterior.cpp",
#    "CStationEncounterTable.cpp",
#    "CTopologyDescTable.cpp",
#    "CSpaceObject.cpp",
#    "CStationEncounterDesc.cpp",
#    "COrderList.cpp",
#    "CIntegerRangeCriteria.cpp",
#    "CInteractionLevel.cpp",
#    "CStaticEffect.cpp",
#    "CBeam.cpp",
#    "COverlayType.cpp",
#    "CMultiverseNewsEntry.cpp",
#    "CShipTable.cpp",
#    "COrbitExactOrder.cpp",
#    "CSquadronID.cpp",
#    "CAscendedObjectList.cpp",
#    "CImageArranger.cpp",
#    "CCXMLWrapper.cpp",
#    "CGateTimerManager.cpp",
#    "CShipArmorDesc.cpp",
#    "CWaveGenerator.cpp",
#    "CTreePathStagateGenerator.cpp",
#    "CPhysicsContactResolver.cpp",
#    "LegacyAIImpl.h",
#    "CStargateDesc.cpp",
#    "LanguageDefs.h",
#    "CEnhancerClass.cpp",
#    "CExtensionCollection.cpp",
#    "CDamageAdjDesc.cpp",
#    "CEngineLanguage.cpp",
#    "CWaitOrder.cpp",
#    "CAIShipControls.cpp",
#    "CSequencerEffect.cpp",
#    "CShip.cpp",
#    "CDriveClass.cpp",
#    "CStationCreateOptions.cpp",
#    "CAutoDockCalc.cpp",
#    "CRegenDesc.cpp",
#    "CMapLabelArranger.cpp",
#    "CEscortOrder.cpp",
#    "CShieldClass.cpp",
#    "CHitCtx.cpp",
#    "CZoanthropeAI.cpp",
#    "CRandomEncounterObjTable.cpp",
#    "CSendMessageOrder.cpp",
#    "CTopologyNodeCriteria.cpp",
#    "CAdventureDesc.cpp",
#    "CAdventureRecord.cpp",
#    "CShipStandard.cpp",
#    "MissileProperties.cpp",
#    "CAreaDamage.cpp",
#    "CApproachOrder.cpp",
#    "CGlobalSpaceObject.cpp",
#    "CrewAIImpl.h",
#    "Utilities.cpp",
#    "CGameRecord.cpp",
#    "CPerceptionCalc.cpp",
#    "CSystemCreateEvents.cpp",
#    "CLocateNodesProc.cpp",
#    "CMultiverseNews.cpp",
#    "CPropertyCompare.cpp",
#    "CLightningBundlePainter.cpp",
#    "CDockScreenPainter.cpp",
#    "I2DFunction.cpp",
#    "CCurrencyBlock.cpp",
#    "CCExtensions.cpp",
#    "CAIBehaviorCtx.cpp",
#    "ObjectImageProperties.cpp",
#    "CShipPerformanceDesc.cpp",
#    "RepairerClassProperties.cpp",
#    "SFXBolt.cpp",
#    "CGlobalEventCache.cpp",
#    "CWeaponFireDesc.cpp",
#    "CMusicResource.cpp",
#    "CArtifactAwakening.cpp",
#    "CContinuousBeam.cpp",
#    "CEffectCreator.cpp",
#    "CRandomTopologyCreator.cpp",
#    "CSoundRef.cpp",
#    "CBaseShipAI.cpp",
#    "CEngineOptions.cpp",
#    "CGameFile.cpp",
#    "ScriptParserImpl.h",
#    "CGaianProcessor.cpp",
#    "CDistributeNodesProc.cpp",
#    "CAbilitySet.cpp",
#    "CConfigurationDesc.cpp",
#    "SFXRay.cpp",
#    "CCrewAI.cpp",
#    "CMultiverseFileRef.cpp",
#    "CObjectJoint.cpp",
#    "CRandomEncounterTypeTable.cpp",
#    "SFXImageAndTail.cpp",
#    "CShipClass.cpp",
#    "CShipChallengeDesc.cpp",
#    "SFXFlare.cpp",
#    "CSpaceEnvironmentType.cpp",
#    "CAutoTargetCalc.cpp",
#    "CShipAIHelper.cpp",
#    "CDesignCollection.cpp",
#    "TopologyDescImpl.h",
#    "CReactionImpl.cpp",
#    "AIManeuvers.cpp",
#    "CDesignTypeCriteria.cpp",
#    "CDesignTable.cpp",
#    "CTradingServices.cpp",
#    "CTableTopologyProc.cpp",
#    "CItemListManipulator.cpp",
#    "CStatusBarPainter.cpp",
#    "CLocationList.cpp",
#    "Devices.cpp",
#    "CHexarcDownloader.cpp",
#    "CCargoDesc.cpp",
#    "CreateSystem.cpp",
#    "CItemType.cpp",
#    "SFXBeam.cpp",
#    "SFXLightningStorm.cpp",
#    "CObjectTracker.cpp",
#    "CCUtil.cpp",
#    "CAStarPathFinder.cpp",
#    "CCommunicationsStack.cpp",
#    "MissionProperties.cpp",
#    "CShipInteriorDesc.cpp",
#    "CFractalTextureLibrary.cpp",
#    "IPaintList.cpp",
#    "CArmorLimits.cpp",
#    "CCircleRadiusDisruptor.cpp",
#    "CAIDeterModule.cpp",
#    "CTopologyCreateCtx.cpp",
#    "CProgramDesc.cpp",
#    "CNavigateOrder.cpp",
#    "CObjectImage.cpp",
#    "IShipController.cpp",
#    "CSphericalTextureMapper.cpp",
#    "CNavigationPath.cpp",
#    "SFXVariants.cpp",
#    "CPower.cpp",
#    "CImageFilterStack.cpp",
#    "PaintUtilities.cpp",
#    "CNameDesc.cpp",
#    "CSovereign.cpp",
#    "CAttackOrder.cpp",
#    "CLanguageDataBlock.cpp",
#    "CSmartSystemCreateOptions.cpp",
#    "CEffectParamDesc.cpp",
#    "CDockScreenVisuals.cpp",
#    "CHexarcSession.cpp",
#    "CWeaponClass.cpp",
#    "CAdventureHighScoreList.cpp",
#    "CSquadronDesc.cpp",
#    "IPlayerController.cpp",
#    "CShockwaveHitTest.cpp",
#    "CMiscellaneousClass.cpp",
#    "CAttributeDataBlock.cpp",
#    "CPhysicsForceResolver.cpp",
#    "SFXStarbust.cpp",
#    "SovereignProperties.cpp",
#    "Events.cpp",
#    "SystemTypeProperties.cpp",
#    "CRandomEncounterDesc.cpp",
#    "CAccessibilitySettings.cpp",
#    "CDamageSource.cpp",
#    "CScriptParser.cpp",
#    "CSquadronController.cpp",
#    "SFXImage.cpp",
#    "IListData.cpp",
#    "CSystemEventList.cpp",
#    "CSpaceObjectProperties.cpp",
#    "CStandardShipAI.cpp",
#    "CStationHullDesc.cpp",
#    "CItemTable.cpp",
#    "CUserProfile.cpp",
#    "CStationEncounterOverrideTable.cpp",
#    "CFractureEffect.cpp",
#    "CFleetShipAI.cpp",
#    "CSimplePathStargateGenerator.cpp",
#    "CDockScreenType.cpp",
#    "COrbit.cpp",
#    "CAttackDetector.cpp",
#    "CDynamicDesignTable.cpp",
#    "CStationType.cpp",
#    "CSystemSpacePainter.cpp",
#    "CItemEventDispatcher.cpp",
#    "SFXFractalImpl.h",
#    "CPaintOrder.cpp",
#    "ShipProperties.cpp",
#    "CObjectEffectList.cpp",
#    "CItemEnhancement.cpp",
#    "SystemPaintImpl.h",
#    "CItemList.cpp",
#    "StationImpl.h",
#    "ShipClassProperties.cpp",
#    "CDockSession.cpp",
#    "CObjectTrackerCriteria.cpp",
#    "SFXEllipse.cpp",
#    "CParticleEffect.cpp",
#    "CMapGridPainter.cpp",
#    "CPaintHelper.cpp",
#    "CDebugOptions.cpp",
#    "DockSessionProperties.cpp",
#    "CTargetList.cpp",
#    "CSystem.cpp",
#    "CLocationDef.cpp",
#    "CSystemCreateStats.cpp",
#    "SystemProperties.cpp",
#    "BaseShipAIProperties.cpp",
#    "ContantsUtilities.cpp",
#    "CComplexArea.cpp",
#    "CCompositeImageModifiers.cpp",
#    "SFXGlow.cpp",
#    "CFleetCommandAI.cpp",
#    "CGameStats.cpp",
#    "CItemCtx.cpp",
#    "CArmorClass.cpp",
#    "CSpaceObjectCriteria.cpp",
#    "CReactorClass.cpp",
#    "CObjectStats.cpp",
#    "CMissile.cpp",
#    "SFXShockwave.cpp",
#    "CEconomyType.cpp",
#    "SFXDisintegrate.cpp",
#    "CArtifactProgram.cpp",
#    "CDesignPropertyDefinitions.cpp",
#    "Markers.cpp",
#    "CAsteroidDesc.cpp",
#    "CSpaceObjectList.cpp",
#    "SFXImageFracture.cpp",
#    "CSolarDeviceClass.cpp",
#    "CItem.cpp",
#    "CLanguage.cpp",
#    "CMenuData.cpp",
#    "CSpaceObjectGrid.cpp",
#    "CGladiatorAI.cpp",
#    "CArmorItem.cpp",
#    "CDisplayAttributeDefinitions.cpp",
#    "CCompositeImageDesc.cpp",
#    "CDeviceSystem.cpp",
#    "SFXPolyflash.cpp",
#    "COverlayCounterDesc.cpp",
#    "SpaceObjectItemProperties.cpp",
#    "XMLLoader.cpp",
#    "CShipUpdateSet.cpp",
#    "SFXPlasmaSphere.cpp",
#    "CResourceDb.cpp",
#    "CNamedEffects.cpp",
#    "SFXMoltenBolt.cpp",
#    "CNetworkTopologyCreator.cpp",
#    "CCodeChainCtx.cpp",
#    "CSFXOptions.cpp",
#    "CIntegralRotation.cpp",
#    "CConquerNodesProc.cpp",
#    "SFXParticleSystem.cpp",
#    "CGenericType.cpp",
#    "CTileMap.cpp",
#    "CDifferentiatedItem.cpp",
#    "CMission.cpp",
#    "CHullPointsCalculator.cpp",
#    "CSoundResource.cpp",
#    "CTradingDesc.cpp",
#    "CFunctionContextWrapper.cpp",
#    "CTLispConvert.cpp",
#    "CDesignType.cpp",
#    "ShipAIImpl.h",
#    "CMapViewportCtx.cpp",
#    "COrderDesc.cpp",
#    "CGuardOrder.cpp",
#    "CDeviceItem.cpp",
#    "SDamageCtx.cpp",
#    "SFXSmokeTrail.cpp",
#    "CInputKeyPainter.cpp",
#    "GameFileCompatibility.h",
#    "CSpaceObjectPool.cpp",
#    "CTopologyAttributeCriteria.cpp",
#    "CDockScreenStack.cpp",
#    "CAchievementRecord.cpp",
#    "CEnhancementDesc.cpp",
#    "CEffect.cpp",
#    "CInstalledArmor.cpp",
#    "SFXParticleExplosion.cpp",
#    "ItemGeneratorImpl.h",
#    "CPatrolOrder.cpp",
  ]
  deps = [
    "//Alchemy",
  ]
  public_deps = [
    "../Include:TSE",
  ]
  include_dirs = [
    ".",
  ]
}

