config("suppressions") {
  cflags = [
    # TODO(clang): Investigate and fix if possible:
    # The pattern of `if (error = foo()))` is common in the code base.
    "-Wno-parentheses",
    # TODO(clang): Investigate and fix if possible:
    # The pattern of `::fooLog("Something %s", aCString);`
    # is the common in the code base.
    "-Wno-non-pod-varargs",
    # TODO(clang): Investigate and fix if possible:
    "-Wno-inconsistent-missing-override",
    # TODO(clang): Investigate and fix if possible:
    "-Wno-switch",
    # TODO(clang): Investigate and fix if possible:
    "-Wno-pragma-pack",
    # TODO(clang): Investigate and fix if possible:
    "-Wno-microsoft-cast",
    # TODO(clang): Investigate and fix if possible:
    "-Wno-delayed-template-parsing-in-cxx20",
    # TODO(clang): Investigate and fix if possible:
    "-Wno-return-type",
    # TODO(clang): Investigate and fix if possible:
    "-Wno-nonportable-include-path",
    # TODO(clang): Investigate and fix if possible:
    # e.g. if (header.bfType != 'MB')
    "-Wno-multichar",
    # TODO(clang): Investigate and fix if possible:
    # e.g. á in "Barják András"
    "-Wno-invalid-source-encoding",
  ]
}

config("compiler") {
  configs = [
    ":suppressions",
    ":runtime_library",
  ]
  cflags = [
    # TODO(clang): enable -Wall
    #"-Wall",
    # TODO(clang): enable -Wextra
    #"-Wextra",
    # TODO(clang): enable -Werror
    #"-Werror",
    "-fcolor-diagnostics",
  ]

  if (is_win) {
    cflags += [
      "-fms-extensions",
      "-fms-compatibility-version=19",
      "-fdelayed-template-parsing",
    ]
  }

  cflags_cc = [ "-std=c++20" ]
  cflags_objcc = [ "-std=c++20" ]
}


config("symbols") {
  ldflags = [ "-g" ]
  cflags = [ "-g" ]
}

config("debug") {
  cflags = [
    "-O0",
  ]
}

config("nostd") {
  cflags = [
    "-nostdlibinc",
  ]
  ldflags = [
    "-nostdlib",
  ]
}

config("nostd++") {
  cflags = [
    "-nostdinc++",
  ]
  ldflags = [
    "-nostdlib++",
  ]
}

config("system_libc++") {
  cflags_cc = ["-stdlib=libc++"]
}

config("release") {
  defines = [ "NDEBUG" ]
  cflags = [ "-O3" ]
}

config("executable_config") {
  ldflags = []
}

config("runtime_library") {
  cflags = []
  cflags_cc = []
  ldflags = []


  if (is_win) {

    ldflags += [
      "-L" + rebase_path("//deps/windows/crt/lib/$current_cpu", root_build_dir),
      "-L" + rebase_path("//deps/windows/sdk/lib/um/$current_cpu", root_build_dir),
      "-L" + rebase_path("//deps/windows/sdk/lib/ucrt/$current_cpu", root_build_dir),
      "-lucrt",
      "-lvcruntime",
      "-lmsvcrt",
      "-lmsvcprt",
      "-lkernel32",
      "-luser32",

      "-lws2_32",
      "-lversion",
      "-lvfw32",
      "-lwinmm",
      "-ldsound",
      "-lodbc32",
      "-lodbccp32",
      "-lshell32",
      "-lgdi32",
      "-ladvapi32",

      "-fms-runtime-lib=dll",

      # Unclear if this is correct or not.
      "--for-linker=-safeseh:no",
    ]

    cflags += [
      "-fms-extensions",
      "-fms-compatibility",
      "-fms-runtime-lib=dll",

      "-isystem" + rebase_path("//deps/windows/crt/include", root_build_dir),
      "-isystem" + rebase_path("//deps/windows/sdk/include/ucrt", root_build_dir),
      "-isystem" + rebase_path("//deps/windows/sdk/include/shared", root_build_dir),
      "-isystem" + rebase_path("//deps/windows/sdk/include/winrt", root_build_dir),
      "-isystem" + rebase_path("//deps/windows/sdk/include/um", root_build_dir),
    ]

    cflags_cc += [
    ]

  }
}

# This group is a dependency of every executable and shared library.
group("common_deps") {
  visibility = [
    ":executable_deps",
    ":loadable_module_deps",
    ":shared_library_deps",
  ]
}

# Only the executable template in BUILDCONFIG.gn should reference this.
group("executable_deps") {
  public_deps = [ ":common_deps" ]
}

# Only the loadable_module template in BUILDCONFIG.gn should reference this.
group("loadable_module_deps") {
  public_deps = [ ":common_deps" ]
}

# Only the shared_library template in BUILDCONFIG.gn should reference this.
group("shared_library_deps") {
  public_deps = [ ":common_deps" ]
}

