source_set("Transcendence") {
  sources = [
    "CGItemDisplayArea.cpp",
    "CSystemMapDisplay.cpp",
    "CCommandLineDisplay.cpp",
    "CDockScreenIconList.cpp",
    "CDaimonListPainter.cpp",
    "CArtifactResultPainter.cpp",
    "CNewGameSession.cpp",
    "CLoadGameSession.cpp",
    "CArtifactStatPainter.cpp",
    "GameSessionCommands.cpp",
    "PlayerController.cpp",
    "GameSession.h",
    "CGTabArea.cpp",
    "GameSettings.h",
    "CChooseAdventureSession.cpp",
    "CGCarouselArea.cpp",
    "CTranscendenceController.cpp",
    "DockScreen.h",
    "Sessions.h",
    "CLoadGameWithSignInTask.cpp",
    "CGDetailsArea.cpp",
    "DefaultKeyMappings.h",
    "CTranscendenceModel.cpp",
    "DockScreenDisplayImpl.h",
    "BackgroundTasks.h",
    "GameSessionAnimate.cpp",
    "CPickerDisplay.cpp",
    "CChangePasswordSession.cpp",
    "PreComp.h",
    "CLoginSession.cpp",
    "CDockScreenCustomList.cpp",
    "CDaimonButtonPainter.cpp",
    "CGNeurohackArea.cpp",
    "CGameSession.cpp",
    "GameScreen.cpp",
    "IDockScreenDisplay.cpp",
    "Transcendence.h",
    "GameStatsAnimation.cpp",
    "CTextCrawlSession.cpp",
    "CDockScreenDetailsPane.cpp",
    "GameOutput.cpp",
    "CDockScreenSelector.cpp",
    "CArtifactMessagePainter.cpp",
    "CGIconListArea.cpp",
    "CGSubjugateArea.cpp",
    "CWaitSession.cpp",
    "KeyboardMapData.h",
    "CHighScoreList.cpp",
    "CGDrawArea.cpp",
    "CGameSettings.cpp",
    "Utilities.cpp",
    "CHelpSession.cpp",
    "CLoadingSession.cpp",
    "CTextCrawlDisplay.cpp",
    "CMenuDisplay.cpp",
    "CUIMessageController.cpp",
    "CDetailList.cpp",
    "CUIResources.cpp",
    "CDockScreenCarousel.cpp",
    "GameSessionInput.cpp",
    "CManeuverController.cpp",
    "CStatsSession.cpp",
    "CIntroShipController.cpp",
    "CDockScreenList.cpp",
    "CMenuDisplayOld.cpp",
    "CDockScreenCustomItemList.cpp",
    "IntroScreen.cpp",
    "Credits.h",
    "CIntroSession.cpp",
    "CAdventureIntroSession.cpp",
    "CGItemListArea.cpp",
    "CKeyboardMapSession.cpp",
    "resource.h",
    "CTranscendenceWnd.cpp",
    "DockScreenSubjugate.h",
    "CModExchangeSession.cpp",
    "CDaimonList.cpp",
    "CNarrativeDisplay.cpp",
    "PlayerShip.h",
    "CGItemListDisplayArea.cpp",
    "CGAreas.h",
    "CodeChainExtensions.cpp",
    "CHeadsUpDisplay.cpp",
    "CIconBarDisplay.cpp",
    "GameSessionDisplays.h",
    "CDockPane.cpp",
    "CGameIconBarData.cpp",
    "CDockScreenItemList.cpp",
    "IntroSession.h",
    "CArtifactAwakenVisuals.cpp",
    "GameSessionMenus.cpp",
    "CDockScreenSubjugate.cpp",
    "CProfileSession.cpp",
    "CArtifactAICorePainter.cpp",
    "CButtonBarDisplay.cpp",
    "CDockScreen.cpp",
    "CDockScreenLayout.cpp",
    "CMessageDisplay.cpp",
    "CTranscendencePlayer.cpp",
    "CGameKeys.cpp",
    "PlayerControllerProperties.cpp",
    "CButtonBarData.cpp",
    "CHighScoreDisplay.cpp",
    "CGSelectorArea.cpp",
    "CGalacticMapSession.cpp",
    "CSystemStationsMenu.cpp",
    "CDetailArea.cpp",
    "CDockScreenActions.cpp",
    "Transcendence.rc",
  ]
  public_deps = [
    "//Alchemy",
    "//Mammoth/TSE",
    "//Mammoth/TSUI",
  ]
  include_dirs = [
    ".",
  ]
}


source_set("TranscendenceMain") {
  sources = [
    "Main.cpp",
  ]
  deps = [
    ":Transcendence",
  ]
}

