
source_set("unittests_empty") {
  testonly = true
  sources = [ "empty_unittest.cc" ]
  deps = [
    "//deps/googletest:gtest",
  ]
}

source_set("unittests_kernel") {
  testonly = true
  sources = [ "kernel_unittest.cc" ]
  deps = [
    "//deps/googletest:gtest",
    "//Alchemy/Kernel",
  ]
}

source_set("unittests_codechain") {
  testonly = true
  sources = [ "codechain_unittest.cc" ]
  deps = [
    "//deps/googletest:gtest",
    "//Alchemy/Kernel",
    "//Alchemy/CodeChain",
  ]
}

source_set("unittests_xmlutil") {
  testonly = true
  sources = [ "xmlutil_unittest.cc" ]
  deps = [
    "//deps/googletest:gtest",
    "//Alchemy/XMLUtil",
  ]
}

source_set("unittests_jpegutil") {
  testonly = true
  sources = [ "jpegutil_unittest.cc" ]
  deps = [
    "//deps/googletest:gtest",
    "//Alchemy/IntelJPEGUtil",
  ]
}

source_set("unittests_tse") {
  testonly = true
  sources = [ "tse_unittest.cc" ]
  deps = [
    "//deps/googletest:gtest",
    "//Mammoth/TSE",
  ]
}

source_set("unittests_tsui") {
  testonly = true
  sources = [ "tsui_unittest.cc" ]
  deps = [
    "//deps/googletest:gtest",
    "//Mammoth/TSUI",
  ]
}

group("unittests") {
  testonly = true
  deps = [
    ":unittests_kernel",
    ":unittests_codechain",
    ":unittests_xmlutil",
    ":unittests_jpegutil",
    ":unittests_empty",
    ":unittests_tse",
    ":unittests_tsui",
  ]
}
