source_set("DirectXUtil") {
  sources = [
    "FilterBlur.cpp",
    "CAniShape.cpp",
    "CDXBackgroundBlt.cpp",
    "CG16bitBinaryRegion.cpp",
    "CompositeCircle.cpp",
    "CG8bitSparseImage.cpp",
    "CG16bitSprite.cpp",
    "CGTextArea.cpp",
    "CIconLabelBlock.cpp",
    "CFrameRateCounter.cpp",
    "DrawImpl.h",
    "CAniSequencer.cpp",
    "CDrawText.cpp",
    "AGArea.cpp",
    "DrawRect.cpp",
    "CPolygonRasterizer.cpp",
    "DrawRegionImpl.h",
    "32bitBlt.cpp",
    "NoiseImpl.h",
    "CG16BitImage.cpp",
    "FilterMinMax.cpp",
    "CDXScreen.cpp",
    "RasterizerImpl.h",
    "PreComp.h",
    "CGShape.cpp",
    "CGRegion.cpp",
    "CGPNG.cpp",
    "CAniButton.cpp",
    "CNoiseGenerator.cpp",
    "CGCloudGenerator3D.cpp",
    "BlendModes.cpp",
    "CScreenMgr3D.cpp",
    "CGFrameArea.cpp",
    "CG32bitImage.cpp",
    "CAniRichText.cpp",
    "16bitDrawGradient.cpp",
    "CGRealChannel.cpp",
    "CReanimator.cpp",
    "CAniImageFill.cpp",
    "Noise.cpp",
    "CAniText.cpp",
    "PixelMacros.h",
    "CAniControl.cpp",
    "DX3DImpl.h",
    "CCloudGenerator.cpp",
    "16bitImageDrawing.cpp",
    "8bitImageDrawing.cpp",
    "CTextBlock.cpp",
    "DrawText.cpp",
    "Files.cpp",
    "CG16bitRegion.cpp",
    "DrawCircle.cpp",
    "CGButtonArea.cpp",
    "CAniCartoucheBlock.cpp",
    "CG8bitImage.cpp",
    "CAniPolygon.cpp",
    "PolygonSimple.cpp",
    "CGlobalEdgeTable.cpp",
    "CGRealHSB.cpp",
    "CListScroller.cpp",
    "Debug.cpp",
    "Sound.cpp",
    "CG16bitRealRegion.cpp",
    "8bitNoise.cpp",
    "8bitDrawCircle.cpp",
    "CAniSolidLine.cpp",
    "Polygon.cpp",
    "DrawClouds.cpp",
    "CLinearAnimator.cpp",
    "CGRunList.cpp",
    "DrawLine.cpp",
    "DirectDraw.cpp",
    "CAniProperty.cpp",
    "CGImageArea.cpp",
    "CAniListBox.cpp",
    "lodepng/lodepng.h",
    "lodepng/lodepng_util.cpp",
    "lodepng/lodepng.cpp",
    "lodepng/pngdetail.cpp",
    "lodepng/lodepng_util.h",
    "CGPath.cpp",
    "DrawQuadCurve.cpp",
    "CG16bitFont.cpp",
    "CLinePainter.cpp",
    "CAniPropertySet.cpp",
    "FilterThreshold.cpp",
    "16bitBlt.cpp",
    "CAniVScroller.cpp",
    "CGRealRGB.cpp",
    "CAniRoundedRect.cpp",
    "CG32bitPixel.cpp",
    "PropertyAnimators.cpp",
    "CGImageCache.cpp",
    "CDXMatrix.cpp",
    "IPropertyAnimator.cpp",
    "CCartoucheBlock.cpp",
    "CSortedEdgeList.cpp",
    "DrawFill.cpp",
    "IAnimatron.cpp",
    "CGlowingRingPainter.cpp",
    "DrawRegion.cpp",
    "CG16bitLinePainter.cpp",
    "CAniRect.cpp",
    "16bitDrawCircle.cpp",
    "AGScreen.cpp",
    "32bitFill.cpp",
    "CAniTextInput.cpp",
    "CAniSolidFill.cpp",
  ]
  public_deps = [
    "../Include:DirectXUtil",
  ]
  deps = [
  ]
  include_dirs = [
    ".",
  ]
}

