config("Include_config") {
  include_dirs = [
    ".",
  ]
}

source_set("Kernel") {
  public = [
    "Kernel.h",
  ]
  sources = [
    "KernelString.h",
  ]
  public_configs = [
    ":Include_config",
  ]
}

source_set("CodeChain") {
  public = [
    "CodeChain.h",
  ]
  sources = [
  ]
  public_configs = [
    ":Include_config",
  ]
}

source_set("Graphics") {
  public = [
    "Graphics.h",
  ]
  sources = [
  ]
  public_configs = [
    ":Include_config",
  ]
}

source_set("Alchemy") {
  public = [
    "Alchemy.h",
  ]
  sources = [
  ]
  public_configs = [
    ":Include_config",
  ]
}

source_set("DirectXUtil") {
  public = [
    "DirectXUtil.h",
  ]
  sources = [
  ]
  public_configs = [
    ":Include_config",
  ]
}

source_set("DirectXFont") {
  public = [
    "DirectXFont.h",
  ]
  sources = [
  ]
  public_configs = [
    ":Include_config",
  ]
}

source_set("XMLUtil") {
  public = [
    "XMLUtil.h",
  ]
  sources = [
  ]
  public_configs = [
    ":Include_config",
  ]
}

source_set("NetUtil") {
  public = [
    "NetUtil.h",
  ]
  sources = [
  ]
  public_configs = [
    ":Include_config",
  ]
}

source_set("IntelJPEGUtil") {
  public = [
    "JPEGUtil.h",
    "IntelJPEGUtil.h",
  ]
  sources = [
  ]
  public_configs = [
    ":Include_config",
  ]
}
