#pragma once

#define ALCHEMY_BUILDFLAG_CAT_INDIRECT(a, b) a##b
#define ALCHEMY_BUILDFLAG_CAT(a, b) ALCHEMY_BUILDFLAG_CAT_INDIRECT(a, b)
#define ALCHEMY_BUILDFLAG(flag) \
  (ALCHEMY_BUILDFLAG_CAT(ALCHEMY_BUILDFLAG_DEFINE_, flag)())

// These flags are used like:
// #if ALCHEMY_BUILDFLAG(ALCHEMY_OS_MAC)
// ...
// #endif

#if defined(__APPLE__)
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_LINUX() 0
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_MAC() 1
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_WINDOWS() 0
#elif defined(__linux__)
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_LINUX() 1
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_MAC() 0
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_WINDOWS() 0
#elif defined(_WIN32)
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_LINUX() 0
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_MAC() 0
#define ALCHEMY_BUILDFLAG_DEFINE_ALCHEMY_OS_WINDOWS() 1
#endif

