name: continuous integration

on: [push, pull_request]

jobs:
  msvc:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: msbuild /m /p:Configuration=Release /p:Platform=Win32 ./Transcendence/Transcendence.sln

  clang:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target_os: [win]
        target_cpu: [x86]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
          sudo apt update
          sudo apt install --install-recommends winehq-stable
      - name: Restore deps cached
        id: cache-deps-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-${{ matrix.target_os }}-${{ matrix.target_cpu }}-deps
          path: |
            deps
      - name: Install deps
        run: ./tools/fetch
      - name: Configure build
        run: ./tools/gn gen --args='target_os="${{ matrix.target_os }}" target_cpu="${{ matrix.target_cpu }}"' out/r
      - name: Build
        run: ./tools/ninja -C out/r
      - name: Store deps cached
        id: cache-deps-store
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}
          path: |
            deps




